DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT (
code INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(50) NOT NULL,
id INT(8) NOT NULL,
age INT(2) NOT NULL,
email VARCHAR(200)
);

INSERT INTO STUDENT (name, id, age, email) VALUES ('Adam', 968, 23, 'ADAM@FIRSTBORN.COM');
INSERT INTO STUDENT (name, id, age, email) VALUES ('kavya', 951, 16, 'kr@ibc.com');